services:
  postgres:
    image: postgres:18.1-alpine
    container_name: petly-postgres
    environment:
      POSTGRES_DB: petly
      POSTGRES_USER: petly
      POSTGRES_PASSWORD: petly
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
